steps:
  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.organization=impesa'
    - '-Dsonar.login=f2ace09cfb53fe5f26aa4c4697cf7b49147b4e4f'
    - '-Dsonar.projectKey=impesa_sonar-test'
    - '-Dsonar.sources=.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        '_GOOGLE_CLOUD_PROJECT=${PROJECT_ID}',
        '-t',
        'gcr.io/$PROJECT_ID/ms-sonar-test:${BRANCH_NAME}-${SHORT_SHA}',
        '.',
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/ms-sonar-test:${BRANCH_NAME}-${SHORT_SHA}"]
    id: "push-project"
images:
  - 'gcr.io/$PROJECT_ID/ms-sonar-test:${BRANCH_NAME}-${SHORT_SHA}'
